name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "lambda_1/**"
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploy
        run: |
          zip -r lambda_1.zip ./lambda_1/*
          aws lambda update-function-code --function-name=lambda_1 --zip-file=fileb://lambda_1.zip
